name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build app
        run: ./scripts/buildprod.sh

        ## Requried Setup for google auth
      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - name: "Use gcloud CLI"
        run: "gcloud info"

        ## Update Docker image
      - name: Build and push Docker image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-474107/notely-ar-repo/notely:latest

        # Run Migrations
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run migrations
        run: ./scripts/migrateup.sh

        ## Deplo
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-474107/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-474107 --max-instances=4

      - name: 24f3003335@ds.study.iitm.ac.in
        run: echo "Hello, world!"
