name: ci

on:
  pull_request:
    branches: [main]

  push:
    branches:
      - main
      - addtest

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Auth Module Test
        run: go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Check Formatting
        run: test -z $(go fmt ./...)

      - name: Install StaticCheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check Linting
        run: staticcheck ./...
